### ISSUE TITLE
Support for helix editor

### ISSUE THREAD

**Issue by realsnick** [oxalica/nil#32]
My current `languages.toml` For `helix` Has the following:

```toml
[[language]]
name = "nix"
scope = "source.nix"
injection-regex = "nix"
file-types = ["nix"]
shebangs = []
roots = []
auto-format = true
formatter = { command = "nixpkgs-fmt" }
comment-token = "#"
language-server = { command = "nil" }
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "nix"
source = { git = "https://github.com/cstrahan/tree-sitter-nix", rev = "6b71a810c0acd49b980c50fc79092561f7cee307" }⏎                         snick@snick-desktop ~/C/flake (main)> 
``` 

The code completion seems to work only for what is local to the file but does not show available functions from source. Is that the expected behavior?
